/**
 * Seeds CDL practice tests for all 8 endorsements.
 * Run: npx tsx scripts/seed-cdl-tests.ts
 */
process.env.NODE_ENV = 'development'

import { getPayload } from 'payload'
import config from '../src/payload.config'

const GENERAL_KNOWLEDGE_QUESTIONS = [
  { q: 'What is the minimum tread depth required for front tires on a commercial vehicle?', answers: [['4/32 inch', true], ['2/32 inch', false], ['6/32 inch', false], ['1/32 inch', false]], exp: 'Front tires must have at least 4/32 inch tread depth. All other tires require a minimum of 2/32 inch.' },
  { q: 'During a pre-trip inspection, you discover an oil leak. What should you do?', answers: [['Do not drive until the problem is fixed', true], ['Drive carefully and monitor the leak', false], ['Add more oil and continue your route', false], ['Report it after completing your delivery', false]], exp: 'Any defects that could affect safety must be repaired before driving. An oil leak can lead to engine failure or a fire.' },
  { q: 'What is the most important reason for doing a vehicle inspection?', answers: [['Your safety and the safety of others', true], ['To comply with DOT regulations', false], ['To avoid fines at weigh stations', false], ['To keep a record for your employer', false]], exp: 'While compliance matters, the primary reason is safety — yours and everyone else on the road.' },
  { q: 'How far ahead should you look when driving on a highway?', answers: [['12–15 seconds', true], ['5–8 seconds', false], ['3–4 seconds', false], ['20–25 seconds', false]], exp: 'At highway speeds, looking 12–15 seconds ahead gives you time to identify and respond to hazards. At 60 mph, that\'s roughly a quarter mile.' },
  { q: 'What does "controlled braking" mean?', answers: [['Applying firm, steady brake pressure without locking wheels', true], ['Using the parking brake to slow down', false], ['Applying brakes hard enough to lock the wheels', false], ['Pumping the brakes rapidly', false]], exp: 'Controlled braking means applying the maximum braking force without locking the wheels, which maintains steering control.' },
  { q: 'When should you downshift before going down a long, steep grade?', answers: [['Before you start down the hill', true], ['Halfway down the hill', false], ['When you feel your speed increasing', false], ['At the bottom of the hill', false]], exp: 'You must select the correct gear before starting down. Once you\'re moving fast, it may be impossible to shift.' },
  { q: 'What is the proper way to use the brake pedal when driving on a slippery road?', answers: [['Apply light, steady pressure', true], ['Pump the brakes quickly', false], ['Apply hard pressure immediately', false], ['Use only the engine brake', false]], exp: 'Hard or sudden braking on slippery roads can cause skids. Light, steady pressure gives you more control.' },
  { q: 'How many hours of off-duty time are required before a driver can reset their 60/70-hour clock?', answers: [['34 consecutive hours', true], ['24 consecutive hours', false], ['10 consecutive hours', false], ['48 consecutive hours', false]], exp: 'A 34-hour restart allows drivers to reset their 60-hour/7-day or 70-hour/8-day clock after taking 34 consecutive hours off duty.' },
  { q: 'What is the "danger zone" around a truck where the driver cannot see other vehicles?', answers: [['The blind spots on all four sides of the vehicle', true], ['The area directly behind the trailer', false], ['Only the right side of the truck', false], ['The area directly in front of the cab', false]], exp: 'Large trucks have blind spots on all four sides — directly in front, directly behind, and along both sides.' },
  { q: 'When backing a truck, you should:', answers: [['Use a spotter when available and back slowly', true], ['Back as quickly as possible', false], ['Always use only your mirrors', false], ['Avoid using your horn', false]], exp: 'You should use a spotter whenever possible, back slowly, and use all mirrors. If you must back without a spotter, get out and walk the area first.' },
  { q: 'What is the minimum following distance for a truck under normal conditions at highway speeds?', answers: [['1 second for every 10 feet of vehicle length', true], ['2 car lengths', false], ['3 seconds', false], ['4 seconds for every 10 feet of vehicle length', false]], exp: 'The rule is one second for every 10 feet of vehicle length at speeds under 40 mph. Add one more second for speeds over 40 mph.' },
  { q: 'If your vehicle has a manual transmission, when is it OK to coast in neutral downhill?', answers: [['Never — it is illegal and dangerous', true], ['Only on grades steeper than 6%', false], ['Only for short distances', false], ['Only when your brakes are overheating', false]], exp: 'Coasting in neutral removes engine braking and reduces your control. It is illegal in most states and always dangerous.' },
  { q: 'What should you do if a tire blows out while driving?', answers: [['Hold the steering wheel firmly, stay off the brakes, and let the vehicle slow down', true], ['Brake hard immediately', false], ['Pull the parking brake', false], ['Swerve to the shoulder immediately', false]], exp: 'Sudden braking after a blowout can cause a loss of control. Hold the wheel firmly, avoid braking, and allow the vehicle to slow gradually.' },
  { q: 'The total stopping distance of a truck is made up of:', answers: [['Perception distance, reaction distance, and braking distance', true], ['Reaction distance only', false], ['Braking distance only', false], ['Reaction distance and braking distance only', false]], exp: 'Total stopping distance includes perception time (seeing the hazard), reaction time (foot to brake), and actual braking distance.' },
  { q: 'What is the maximum number of hours a property-carrying driver can drive in a 14-hour window?', answers: [['10 hours', true], ['11 hours', false], ['12 hours', false], ['14 hours', false]], exp: 'Under FMCSA HOS rules, a property-carrying driver may drive a maximum of 11 hours after 10 consecutive hours off duty, but only within a 14-hour window.' },
  { q: 'When is it safe to remove the radiator cap to check coolant level?', answers: [['Only when the engine has cooled down', true], ['Only when the engine is running', false], ['Any time, as long as you use a cloth', false], ['Only after driving at least 30 minutes', false]], exp: 'Never remove the radiator cap on a hot engine — steam and boiling coolant can cause severe burns.' },
  { q: 'What does a "placarded" vehicle mean?', answers: [['The vehicle is carrying hazardous materials', true], ['The vehicle has passed DOT inspection', false], ['The vehicle has oversized cargo', false], ['The vehicle is exempt from weigh station stops', false]], exp: 'Placards are diamond-shaped signs required on vehicles carrying hazardous materials.' },
  { q: 'What should you do when you are being tailgated?', answers: [['Increase your following distance from the vehicle ahead', true], ['Tap your brakes to warn the driver', false], ['Speed up to create more distance', false], ['Slow down abruptly', false]], exp: 'Increasing your following distance gives you more time to brake gradually, reducing the chance the tailgater will rear-end you.' },
  { q: 'Cargo must be secured to prevent it from shifting. How often must you check cargo securement during a trip?', answers: [['Within the first 50 miles, then every 3 hours or 150 miles', true], ['Only at the start of the trip', false], ['Every hour', false], ['Only when you stop for fuel', false]], exp: 'FMCSA requires a cargo check within the first 50 miles, and then at every change of duty status, every 3 hours of driving, or every 150 miles.' },
  { q: 'What is "black ice"?', answers: [['A thin, nearly invisible layer of ice on the road surface', true], ['Ice that forms in shaded areas only', false], ['Ice mixed with road debris', false], ['Ice that only forms at night', false]], exp: 'Black ice is a thin transparent layer of ice that looks like wet pavement. It is extremely dangerous because it is very difficult to see.' },
  { q: 'Which of the following is NOT a sign of tire failure?', answers: [['Increased fuel efficiency', true], ['Steering that feels heavy or pulling to one side', false], ['A loud bang or pop', false], ['Vibration or thumping sounds', false]], exp: 'Increased fuel efficiency has no connection to tire failure. All other options are classic warning signs.' },
  { q: 'When driving through a curve, you should:', answers: [['Slow down before the curve and accelerate gradually coming out', true], ['Accelerate through the curve to maintain momentum', false], ['Brake while in the curve to control speed', false], ['Stay in the center of the lane at all times', false]], exp: 'Braking in a curve can cause skids. The correct technique is to reduce speed before entering the curve and gently accelerate as you exit.' },
  { q: 'What is the correct procedure if your brakes fail on a downgrade?', answers: [['Downshift and steer to an escape ramp or open area', true], ['Turn off the engine', false], ['Pump the brakes rapidly', false], ['Swerve side to side to slow down', false]], exp: 'If brakes fail on a downgrade, downshift to use engine braking, look for an escape ramp, and steer toward any open area.' },
  { q: 'Which statement about speed and stopping distance is correct?', answers: [['Doubling your speed quadruples your stopping distance', true], ['Doubling your speed doubles your stopping distance', false], ['Doubling your speed triples your stopping distance', false], ['Speed has no effect on stopping distance', false]], exp: 'Stopping distance increases with the square of your speed. Double your speed, and stopping distance increases four times.' },
  { q: 'After fueling, what should you do before driving away?', answers: [['Check that all fuel caps are secured', true], ['Run the engine for 5 minutes', false], ['Check your mirrors only', false], ['Log the fuel purchase in your logbook first', false]], exp: 'Unsecured fuel caps can cause fuel spills, fire hazards, and failed inspections. Always verify caps are tight before moving.' },
]

const AIR_BRAKES_QUESTIONS = [
  { q: 'What compresses the air in an air brake system?', answers: [['The air compressor', true], ['The brake pedal', false], ['The air tanks', false], ['The relay valves', false]], exp: 'The air compressor, driven by the engine, compresses air and pumps it into the storage tanks.' },
  { q: 'What is the minimum air pressure that must build in the system before you can drive?', answers: [['100 psi', true], ['50 psi', false], ['80 psi', false], ['120 psi', false]], exp: 'Most systems require at least 100 psi in the air tanks before the low air pressure warning light goes out.' },
  { q: 'What do the air brakes use to stop the vehicle?', answers: [['Compressed air', true], ['Hydraulic fluid', false], ['Vacuum', false], ['Spring pressure only', false]], exp: 'Air brakes use compressed air stored in tanks to apply pressure to the brake chambers.' },
  { q: 'When you apply the brake pedal, what happens to the air pressure?', answers: [['It is released from the brake chambers to apply the brakes', true], ['It increases in the tanks', false], ['It stays the same', false], ['It is released from the compressor', false]], exp: 'Pushing the brake pedal releases air from the brake chambers, allowing the springs to apply the brakes.' },
  { q: 'What is the purpose of the air tank drain valve?', answers: [['To drain water and oil from the air tanks', true], ['To release brake pressure', false], ['To fill the tanks with air', false], ['To test the parking brake', false]], exp: 'Moisture and oil accumulate in the tanks and must be drained daily to prevent brake valve freezing and corrosion.' },
  { q: 'How often should you drain the air tanks?', answers: [['At the end of each day of driving', true], ['Once a week', false], ['Only when the low pressure warning comes on', false], ['Never — the system drains automatically', false]], exp: 'Draining daily prevents moisture buildup that can freeze in cold weather and cause brake failure.' },
  { q: 'What does the low air pressure warning signal tell you?', answers: [['The air pressure has dropped to an unsafe level', true], ['The parking brake is set', false], ['The air compressor is running', false], ['The brake pads are worn', false]], exp: 'When pressure drops below 60 psi (or thereabouts), the warning activates. Do not drive until pressure is restored.' },
  { q: 'What should you do if the low air pressure warning comes on while driving?', answers: [['Stop and safely park as soon as possible', true], ['Speed up to build more pressure', false], ['Continue driving normally', false], ['Pump the brake pedal', false]], exp: 'Low pressure means your brakes may not work. Stop safely before you lose braking ability.' },
  { q: 'What is a dual air brake system?', answers: [['Two separate air brake systems that share a single set of controls', true], ['A system with two air compressors', false], ['Brakes that work on two axles only', false], ['A backup brake system', false]], exp: 'Dual systems have two separate air brake systems (primary and secondary) for redundancy. One set of controls operates both.' },
  { q: 'What keeps the brakes applied when the parking brake control is pushed in?', answers: [['Spring pressure in the brake chambers', true], ['Air pressure', false], ['Hydraulic fluid', false], ['The brake pedal lock', false]], exp: 'The parking brake uses strong springs. Pushing the control releases air that was holding the springs back.' },
  { q: 'To release the parking brake, the driver must:', answers: [['Build enough air pressure, then push the parking brake control in', true], ['Pump the brake pedal 10 times', false], ['Pull the control out', false], ['Turn off the engine', false]], exp: 'Air pressure must be built to push back the springs. Then the parking brake control can be pushed in to release.' },
  { q: 'Why do heavy vehicles use air brakes instead of hydraulic brakes?', answers: [['Air brakes can store energy and are more reliable for heavy loads', true], ['Hydraulic fluid is too expensive', false], ['Air brakes are required by law for all trucks', false], ['Hydraulic brakes do not work on slopes', false]], exp: 'Air brakes can store energy in reservoirs, handle heat better for heavy loads, and have fail-safe spring brakes.' },
  { q: 'What is the purpose of the supply pressure gauge?', answers: [['To show how much air pressure is in the air tanks', true], ['To show brake application pressure', false], ['To indicate compressor speed', false], ['To measure fuel level', false]], exp: 'The supply (or reservoir) gauge shows the pressure in the air tanks. This is what you watch when building air.' },
  { q: 'A fully charged air brake system typically has how much pressure?', answers: [['125 psi', true], ['60 psi', false], ['90 psi', false], ['200 psi', false]], exp: 'Normal operating range is about 100–125 psi. Compressors cut out around 125 psi and cut in around 100 psi.' },
  { q: 'What happens when the brake pedal is released?', answers: [['Air pressure is restored to the brake chambers, releasing the brakes', true], ['The parking brake engages', false], ['The air tanks drain', false], ['Nothing — brakes stay applied', false]], exp: 'Releasing the pedal closes the supply valve and opens the exhaust, allowing air back into the chambers.' },
  { q: 'During a pre-trip inspection, what should you check on the brake system?', answers: [['Air pressure buildup, leaks, and low pressure warning', true], ['Only the brake pedal feel', false], ['Just the parking brake', false], ['Nothing — brakes are self-checking', false]], exp: 'You must verify pressure builds correctly, the warning works, and there are no audible air leaks.' },
  { q: 'What causes "brake fade"?', answers: [['Excessive heat that reduces braking power', true], ['Low air pressure', false], ['Worn brake pads', false], ['Water in the air tanks', false]], exp: 'Repeated hard braking heats the drums or rotors. Overheated brakes lose effectiveness.' },
  { q: 'What is the proper way to slow down when using air brakes?', answers: [['Use the brakes in combination with engine braking', true], ['Ride the brakes constantly', false], ['Use only the trailer brakes', false], ['Downshift without using brakes', false]], exp: 'Combine controlled brake application with proper gear selection. Avoid prolonged braking that causes fade.' },
  { q: 'If the spring brakes come on while driving, you should:', answers: [['Safely stop as soon as you can — you have a serious brake problem', true], ['Continue driving to the next exit', false], ['Pump the brake pedal', false], ['Accelerate to build air pressure', false]], exp: 'Spring brakes engage when air pressure is too low. This indicates a leak or compressor failure. Stop immediately.' },
  { q: 'What is the "cracked" method of applying brakes?', answers: [['Slightly pressing the brake pedal to apply brakes gradually', true], ['Pumping the brakes rapidly', false], ['Holding the brake halfway', false], ['Using only the parking brake', false]], exp: 'The crack method means applying light, steady pressure so brakes engage smoothly without locking.' },
  { q: 'Which type of brake is the parking brake?', answers: [['Spring brake', true], ['Disc brake', false], ['Drum brake', false], ['Emergency brake only', false]], exp: 'The parking brake uses spring-activated brake chambers. Air pressure holds them off; low pressure applies them.' },
  { q: 'What does an air compressor do in the brake system?', answers: [['Pumps air into the storage tanks', true], ['Releases air from the brakes', false], ['Cools the brake drums', false], ['Charges the battery', false]], exp: 'The compressor is powered by the engine and continuously pumps compressed air into the reservoir tanks.' },
  { q: 'When should you use the parking brake?', answers: [['Whenever you park the vehicle', true], ['Only on steep hills', false], ['Never — use wheel chocks only', false], ['Only when the air pressure is low', false]], exp: 'Always set the parking brake when parking. Never rely on transmission alone to hold the vehicle.' },
  { q: 'What happens if you leave the parking brake on while driving?', answers: [['You can damage the brakes and may not build air pressure', true], ['Nothing — it will disengage automatically', false], ['The brakes will work better', false], ['The engine will stall', false]], exp: 'Driving with the parking brake on creates heat and can damage brakes. Air pressure may not build properly.' },
  { q: 'How can you check that the spring brakes come on automatically?', answers: [['Chock the wheels, release the parking brake, and step on the brake pedal until pressure drops', true], ['Just look at the gauges', false], ['Listen for air leaks', false], ['Drive in reverse', false]], exp: 'The spring brake test: with wheels chocked, release the parking brake, fan off the service brake until pressure drops. Spring brakes should apply before 20 psi.' },
  { q: 'What is the first thing you should do when the low air pressure warning activates?', answers: [['Stop and safely park the vehicle', true], ['Speed up', false], ['Turn off the engine', false], ['Pull the parking brake knob', false]], exp: 'The warning means pressure is dangerously low. Brakes may fail. Stop as soon as safely possible.' },
]

const HAZMAT_QUESTIONS = [
  { q: 'Who is responsible for ensuring hazardous materials are properly placarded?', answers: [['The driver', true], ['The shipper only', false], ['The receiver only', false], ['The loading dock workers', false]], exp: 'The driver is responsible for verifying correct placarding before driving. You can be cited for missing or wrong placards.' },
  { q: 'Where must you keep the shipping papers for hazardous materials?', answers: [['In a place that is readily accessible and within reach while seated', true], ['In the sleeper compartment', false], ['In a locked toolbox', false], ['In the trailer', false]], exp: 'Shipping papers must be within reach of the driver (e.g., pouch on door or seat) for quick access during inspections or emergencies.' },
  { q: 'What is a hazardous materials shipper\'s responsibility?', answers: [['To describe the material properly and package it correctly', true], ['To drive the load to its destination', false], ['To provide the trailer', false], ['To load the cargo only', false]], exp: 'Shippers must classify materials, use proper packaging, mark and label, and prepare accurate shipping papers.' },
  { q: 'When must you stop before crossing railroad tracks when hauling hazmat?', answers: [['Always — for Division 1.1, 1.2, or 1.3 explosives and some other materials', true], ['Only at night', false], ['Never — trucks never stop at tracks', false], ['Only when the crossing has no gates', false]], exp: 'Certain hazard classes (e.g., explosives, poison inhalation hazard) require stopping before railroad crossings. Check your load.' },
  { q: 'Which hazard class covers flammable liquids?', answers: [['Class 3', true], ['Class 1', false], ['Class 2', false], ['Class 4', false]], exp: 'Class 3 is Flammable Liquids (e.g., gasoline, diesel, alcohol). Class 1 is Explosives, Class 2 is Gases, Class 4 is Flammable Solids.' },
  { q: 'What does the number in the bottom corner of a placard indicate?', answers: [['The UN/NA identification number for the material', true], ['The hazard class', false], ['The weight of the load', false], ['The shipper\'s ID', false]], exp: 'The 4-digit UN or NA number identifies the specific hazardous material and is used for emergency response.' },
  { q: 'How close can you park to an open fire when carrying hazardous materials?', answers: [['300 feet', true], ['50 feet', false], ['100 feet', false], ['500 feet', false]], exp: 'You must park at least 300 feet from an open fire when carrying hazardous materials. Some materials have greater restrictions.' },
  { q: 'What should you do if you are in an accident involving hazardous materials?', answers: [['Keep people away, call 911, and identify the materials from shipping papers', true], ['Move the vehicle off the road and leave', false], ['Only call your company', false], ['Attempt to clean up the spill yourself', false]], exp: 'Protect people from exposure, report the incident, and provide emergency responders with the shipping papers and placard info.' },
  { q: 'Which document lists the hazard class, proper shipping name, and ID number for your load?', answers: [['The shipping paper (bill of lading)', true], ['The insurance certificate', false], ['The fuel receipt', false], ['The logbook', false]], exp: 'Shipping papers must include the proper shipping name, hazard class, UN/NA number, and other required information.' },
  { q: 'What does "RSPA" stand for in hazmat regulations?', answers: [['Research and Special Programs Administration (now PHMSA)', true], ['Regional Safety and Placard Association', false], ['Railroad Shipping and Placard Association', false], ['It is not a hazmat term', false]], exp: 'RSPA was the former name of the agency now known as PHMSA (Pipeline and Hazardous Materials Safety Administration).' },
  { q: 'When can you park a placarded vehicle in a congested area?', answers: [['Only when necessary for pick-up or delivery, and never near open flames', true], ['Whenever you need a break', false], ['At any truck stop', false], ['Only during daylight hours', false]], exp: 'Parking placarded vehicles in crowded areas is restricted. Park only when required for loading/unloading, away from people and fire.' },
  { q: 'What is the purpose of the Emergency Response Guidebook (ERG)?', answers: [['To provide initial response guidance for hazmat incidents', true], ['To list all hazmat routes', false], ['To replace shipping papers', false], ['To train new drivers', false]], exp: 'The ERG helps first responders identify materials and take initial protective actions. You should have one in the cab.' },
  { q: 'Who must provide the driver with the required hazmat training?', answers: [['The employer', true], ['The shipper', false], ['The DOT', false], ['The driver must train themselves', false]], exp: 'Employers must provide hazmat training (general awareness, function-specific, safety, security). Training must be renewed every 3 years.' },
  { q: 'What is a "radioactive" placard color scheme?', answers: [['White on yellow with the trefoil symbol', true], ['Red and white stripes', false], ['Orange', false], ['Green', false]], exp: 'Radioactive materials use a white-on-yellow placard with the radiation trefoil symbol. Class 7.' },
  { q: 'When loading hazardous materials, you should:', answers: [['Check that packaging is not damaged and that you have the correct materials', true], ['Assume the shipper loaded everything correctly', false], ['Load as quickly as possible', false], ['Only load during the day', false]], exp: 'Drivers must verify cargo matches shipping papers, packaging is intact, and there are no leaks or damage before driving.' },
  { q: 'What does a "Poison" or "Toxic" placard indicate?', answers: [['Materials that can cause harm through ingestion, inhalation, or skin contact', true], ['Materials that are only harmful if swallowed', false], ['Materials that are safe to touch', false], ['Materials that are only flammable', false]], exp: 'Poisons (Class 6) can be toxic by various routes. Poison Inhalation Hazard (PIH) materials have additional restrictions.' },
  { q: 'How often must a hazmat endorsement holder renew their background check?', answers: [['At least every 5 years (or as required by TSA)', true], ['Every year', false], ['Every 10 years', false], ['Only when renewing the CDL', false]], exp: 'TSA requires a security threat assessment for hazmat endorsement holders. It must be current for the endorsement to be valid.' },
  { q: 'What should you do if you discover a leak in a container of hazardous materials?', answers: [['Move away from the leak, warn others, and call for help', true], ['Try to plug the leak', false], ['Drive to the nearest repair shop', false], ['Ignore it if it is a small leak', false]], exp: 'Do not attempt to repair leaks. Move to a safe distance, keep people away, and contact emergency services. Use the ERG.' },
  { q: 'Which class covers oxidizers?', answers: [['Class 5', true], ['Class 3', false], ['Class 1', false], ['Class 8', false]], exp: 'Class 5 is Oxidizers (substances that can cause or contribute to combustion). Class 8 is Corrosive.' },
  { q: 'When transporting explosives, you must:', answers: [['Follow all route restrictions and avoid tunnels if required', true], ['Drive only at night', false], ['Use only rural roads', false], ['Never stop', false]], exp: 'Explosives (Class 1) have strict routing rules. Some loads are prohibited from tunnels, crowded areas, or certain roads.' },
  { q: 'What is a "corrosive" material?', answers: [['A material that can destroy skin or metal through chemical action', true], ['A material that burns easily', false], ['A material that explodes', false], ['A material that glows in the dark', false]], exp: 'Class 8 Corrosives can cause severe damage to tissue or materials. Examples: acids, bleach, battery acid.' },
  { q: 'Before driving with hazardous materials, you must:', answers: [['Review shipping papers and inspect the load and placards', true], ['Only check the truck\'s mechanical condition', false], ['Get a special permit from the state', false], ['Call the shipper', false]], exp: 'You must verify shipping papers, inspect cargo and packaging, confirm correct placarding, and ensure no damage or leaks.' },
  { q: 'What does "ORD" mean on a placard?', answers: [['Other Regulated Material (ORM-D, now Limited Quantity)', true], ['Order', false], ['Orange', false], ['It is not a standard placard term', false]], exp: 'ORM-D (Other Regulated Material) was used for consumer commodities. Many are now shipped under Limited Quantity rules.' },
  { q: 'When must you have placards on your vehicle?', answers: [['When the load meets the quantity thresholds that require placarding', true], ['Only for explosives', false], ['Only when crossing state lines', false], ['Never — placards are optional', false]], exp: 'Placards are required when the load meets the placarding quantity for the material. Some materials are always placarded.' },
  { q: 'What is the first step in a hazmat pre-trip inspection?', answers: [['Check shipping papers against the load and placards', true], ['Check tire pressure', false], ['Start the engine', false], ['Inspect the fifth wheel', false]], exp: 'Verify the load matches the shipping papers, placards are correct and readable, and packaging shows no damage or leaks.' },
  { q: 'Who enforces hazardous materials regulations?', answers: [['DOT/PHMSA and other federal and state agencies', true], ['Only the FBI', false], ['Only the shipper', false], ['Only the carrier', false]], exp: 'PHMSA (under DOT), FMCSA, and state agencies enforce hazmat rules. Violations can result in serious fines and penalties.' },
]

const COMBINATION_QUESTIONS = [
  { q: 'What is a combination vehicle?', answers: [['A vehicle with a power unit and one or more trailers', true], ['A truck with two engines', false], ['A truck and bus together', false], ['Any vehicle over 26,000 pounds', false]], exp: 'A combination vehicle is a truck tractor or truck plus one or more trailers. Class A CDL typically requires combination vehicle knowledge.' },
  { q: 'What is the fifth wheel?', answers: [['The coupling device that connects the tractor to the trailer', true], ['A type of steering axle', false], ['The fifth axle on a trailer', false], ['A brake component', false]], exp: 'The fifth wheel is the coupling mechanism on the tractor that locks with the trailer kingpin to connect tractor and trailer.' },
  { q: 'What is the proper way to check that the fifth wheel is locked?', answers: [['Pull the tractor forward gently against the trailer with trailer brakes set', true], ['Back under the trailer at high speed', false], ['Check visually only', false], ['Lift the trailer with the landing gear', false]], exp: 'Set the trailer brakes and pull forward gently. If the fifth wheel is locked, the tractor will not separate from the trailer.' },
  { q: 'When coupling a tractor and trailer, where should the kingpin be?', answers: [['In the center of the fifth wheel', true], ['Slightly to the rear', false], ['Slightly to the front', false], ['It does not matter', false]], exp: 'The kingpin must be centered in the fifth wheel for proper coupling. Off-center coupling can cause dangerous separation.' },
  { q: 'How much space should you have between the tractor and trailer when backing under a trailer?', answers: [['About 1/4 inch', true], ['At least 6 inches', false], ['No space — they must touch', false], ['2 inches', false]], exp: 'Leave about 1/4 inch. Too much space can damage components; too little can cause improper locking.' },
  { q: 'What should you do after coupling a trailer?', answers: [['Connect air and electrical lines, then raise the landing gear', true], ['Raise the landing gear first', false], ['Drive away immediately', false], ['Only connect the air lines', false]], exp: 'Connect glad hands and pigtails first. Ensure the trailer is supported, then raise the landing gear before driving.' },
  { q: 'When uncoupling, in what order should you perform the steps?', answers: [['Position, set trailer brakes, lower landing gear, disconnect lines, then release fifth wheel', true], ['Release fifth wheel first', false], ['Disconnect lines while moving', false], ['Lower landing gear before setting brakes', false]], exp: 'Position the rig, set the trailer brakes, lower the landing gear, disconnect air/electrical lines, then release the fifth wheel latch.' },
  { q: 'What can happen if you cross the air lines when coupling?', answers: [['The trailer brakes may not work properly, or may lock up', true], ['Nothing — the lines are interchangeable', false], ['The tractor will not start', false], ['Only the turn signals will fail', false]], exp: 'Crossed glad hands can cause the trailer to apply brakes when the tractor brakes release, or vice versa — very dangerous.' },
  { q: 'What color are the emergency (supply) air lines?', answers: [['Red', true], ['Blue', false], ['Yellow', false], ['Black', false]], exp: 'Red = emergency/supply line (controls trailer spring brakes). Blue/yellow = service line (controls trailer brake application).' },
  { q: 'What color is the service air line?', answers: [['Blue or black', true], ['Red', false], ['Green', false], ['Yellow only', false]], exp: 'The service line is typically blue or black. It carries the signal to apply the trailer brakes when you press the brake pedal.' },
  { q: 'Why should you use the tractor protection valve when parking?', answers: [['To close the air lines so a broken trailer line does not drain the tractor tanks', true], ['To increase air pressure', false], ['To lock the fifth wheel', false], ['It is not necessary when parking', false]], exp: 'The tractor protection valve (often a red valve) closes the tractor air supply to the trailer. If the trailer lines break, your tractor keeps its air.' },
  { q: 'What is the danger of a "trailer jackknife"?', answers: [['The trailer swings around and can strike the cab or other vehicles', true], ['The landing gear breaks', false], ['The kingpin cracks', false], ['The air lines tangle', false]], exp: 'Jackknifing occurs when the trailer swings sharply toward the tractor, often due to braking too hard on slippery roads.' },
  { q: 'How does a trailer brake hand valve (trolley valve) work?', answers: [['It applies the trailer brakes independently of the tractor', true], ['It applies the tractor brakes only', false], ['It releases the parking brake', false], ['It is used only for testing', false]], exp: 'The hand valve allows you to apply trailer brakes independently, useful when descending grades or testing the trailer brakes.' },
  { q: 'Before driving a combination vehicle, you should:', answers: [['Test the trailer brakes with the hand valve before moving', true], ['Assume they work if the tractor brakes work', false], ['Only test at highway speed', false], ['Skip the test if you are in a hurry', false]], exp: 'You must verify the trailer brakes respond. Use the hand valve while the tractor is stationary to ensure the trailer brakes apply.' },
  { q: 'What is "off-tracking"?', answers: [['When the rear wheels of the trailer follow a different path than the tractor', true], ['When the trailer goes off the road', false], ['When the fifth wheel disconnects', false], ['When the brakes fail', false]], exp: 'Off-tracking means the trailer wheels cut inside on turns. The longer the rig, the more off-tracking. Plan turns accordingly.' },
  { q: 'When turning a combination vehicle, you should:', answers: [['Wide right turns to avoid the trailer cutting the corner', true], ['Turn sharply to minimize off-tracking', false], ['Stay in the left lane', false], ['Never turn right', false]], exp: 'Turn wide enough so the trailer does not run over curbs or hit obstacles. The trailer tracks inside the tractor path.' },
  { q: 'What happens if the trailer has no brakes?', answers: [['The trailer can push the tractor, causing a jackknife or loss of control', true], ['Nothing — the tractor brakes are enough', false], ['The trailer will automatically brake', false], ['You will get a warning light only', false]], exp: 'Without trailer brakes, the trailer\'s momentum can push the tractor sideways or cause a jackknife, especially on curves or when braking.' },
  { q: 'How often should you check that the trailer is still coupled when driving?', answers: [['At every stop and periodically in your mirrors', true], ['Only at the start of the trip', false], ['Never — you cannot see it', false], ['Only at weigh stations', false]], exp: 'Check your mirrors regularly. At stops, verify the fifth wheel area and that the trailer is still secure. Look for separation or unusual movement.' },
  { q: 'What is the purpose of the landing gear?', answers: [['To support the front of the trailer when it is not connected to a tractor', true], ['To lift the trailer for tire changes', false], ['To connect the air lines', false], ['To lock the fifth wheel', false]], exp: 'Landing gear (crank stands) support the front of the trailer when it is disconnected. Always ensure they are fully raised before driving.' },
  { q: 'When backing a combination vehicle, you should:', answers: [['Turn the steering wheel in the opposite direction you want the trailer to go', true], ['Turn the wheel the same direction as the trailer', false], ['Never back a combination vehicle', false], ['Use only the mirrors', false]], exp: 'To back a trailer left, turn the steering wheel right (and vice versa). "Steer toward the problem" — if the trailer goes too far left, steer left to correct.' },
  { q: 'What should you do if the trailer begins to swing (fishtail) while driving?', answers: [['Release the brakes and accelerate slightly to stabilize, then brake gently', true], ['Brake harder', false], ['Steer sharply', false], ['Pull the parking brake', false]], exp: 'Hard braking worsens a fishtail. Ease off the brakes and apply power gently to straighten the rig, then slow down gradually.' },
  { q: 'How do you know if the trailer brakes are working?', answers: [['You should feel a slight drag when applying the brake pedal', true], ['There is no way to tell', false], ['The tractor slows down only', false], ['A light on the dash', false]], exp: 'When you apply the brakes, you should feel the trailer contributing to the stop. If the rig slows but feels "loose," trailer brakes may be out.' },
  { q: 'What is a "glad hand"?', answers: [['The connector that couples the air lines between tractor and trailer', true], ['A type of fifth wheel', false], ['The hand brake valve', false], ['A mirror adjustment', false]], exp: 'Glad hands are the couplers on the ends of the air hoses. They connect the tractor air supply to the trailer brake system.' },
  { q: 'After connecting the air lines, what should you do?', answers: [['Listen for air leaks and ensure pressure builds in the trailer', true], ['Nothing — drive away', false], ['Disconnect and reconnect', false], ['Only check the service line', false]], exp: 'Listen for leaks. Build air pressure and verify the trailer reservoirs charge. A loss of pressure or audible leaks indicates a problem.' },
  { q: 'What is the proper following distance for a combination vehicle?', answers: [['At least one second per 10 feet of length, plus one second at 40+ mph', true], ['Same as a car', false], ['2 seconds', false], ['10 seconds', false]], exp: 'Combination vehicles need more space due to weight and length. One second per 10 feet; add one second for speeds over 40 mph.' },
  { q: 'When going down a long grade with a combination vehicle, you should:', answers: [['Use a low gear and apply brakes intermittently, not continuously', true], ['Ride the brakes the whole way', false], ['Use neutral to save fuel', false], ['Speed up to get down faster', false]], exp: 'Use a low gear for engine braking. Apply brakes in short bursts to control speed. Continuous braking causes brake fade.' },
]

const DOUBLES_TRIPLES_QUESTIONS = [
  { q: 'What are double and triple trailers?', answers: [['Combinations of a tractor pulling two or three trailers', true], ['Trailers with two or three axles', false], ['Trailers that can carry double or triple the weight', false], ['Tank trailers split into compartments', false]], exp: 'Doubles = tractor + 2 trailers. Triples = tractor + 3 trailers. These require a special endorsement in many states.' },
  { q: 'Which trailer is the "pup"?', answers: [['The shorter trailer, usually the rearmost in a doubles/triples set', true], ['The lead trailer', false], ['The heaviest trailer', false], ['A trailer used only for practice', false]], exp: 'The pup is typically 27–28 feet and is often the second (or third) trailer. The lead trailer is usually longer.' },
  { q: 'Why do doubles and triples require special handling?', answers: [['They have more crack-the-whip effect and are harder to control', true], ['They weigh more than a single trailer', false], ['They are illegal in some states', false], ['They have different brakes', false]], exp: 'Multiple trailers amplify the "crack-the-whip" effect — a small steering input can cause large movements in the rear trailers.' },
  { q: 'What is the "crack-the-whip" effect?', answers: [['When a sudden movement in the front causes amplified sway in the rear trailers', true], ['When the fifth wheel releases', false], ['When brakes lock up', false], ['When accelerating too fast', false]], exp: 'A quick lane change or gust of wind can cause the rear trailer(s) to swing. The effect increases with more trailers.' },
  { q: 'When backing doubles or triples, you should:', answers: [['Only back when absolutely necessary, and do it slowly', true], ['Back as quickly as possible', false], ['Never back — it is illegal', false], ['Disconnect the rear trailers first', false]], exp: 'Backing multiple trailers is difficult and risky. Avoid it when possible. If you must back, go slowly and use a spotter.' },
  { q: 'How does braking differ with doubles and triples?', answers: [['Brakes apply from the rear forward, so you need more stopping distance', true], ['Brakes apply faster than a single trailer', false], ['You use the parking brake for normal stops', false], ['There is no difference', false]], exp: 'Brake application travels from the rear trailers forward. This delay means you need more following distance and earlier braking.' },
  { q: 'What speed restrictions often apply to doubles and triples?', answers: [['Lower speed limits than for single trailers in many states', true], ['Higher limits because they are more stable', false], ['No restrictions', false], ['Only on curves', false]], exp: 'Many states impose lower speed limits for doubles and triples. Check state-specific rules before traveling.' },
  { q: 'When driving doubles or triples, you should avoid:', answers: [['Sudden steering, braking, or acceleration', true], ['Highways', false], ['Empty trailers', false], ['Daytime driving', false]], exp: 'Smooth inputs are critical. Sudden movements can cause the rear trailers to swing or jackknife.' },
  { q: 'What is a "converter dolly"?', answers: [['A device that connects two trailers in a doubles set', true], ['A type of brake valve', false], ['An electrical connection', false], ['A fifth wheel on the tractor', false]], exp: 'The converter dolly (often called a "jiffy" or "pintle" dolly) has a fifth wheel and connects the lead trailer to the pup.' },
  { q: 'How should you steer when the rear trailer begins to drift?', answers: [['Steer gently in the direction you want the rear to go', true], ['Steer sharply the opposite way', false], ['Brake hard', false], ['Accelerate', false]], exp: 'Gentle corrections. Overcorrecting can worsen the sway. Steer in the direction you want the rear trailer to move.' },
  { q: 'What should you check on the converter dolly during a pre-trip?', answers: [['Mounting to the lead trailer, tire condition, lights, and coupling', true], ['Only the tires', false], ['Nothing — it is part of the trailer', false], ['Only the lights', false]], exp: 'Verify the dolly is securely mounted, tires are good, lights work, and the coupling to both trailers is proper.' },
  { q: 'Why is the hand valve especially important with doubles and triples?', answers: [['You can apply trailer brakes separately to control sway', true], ['The tractor brakes do not work', false], ['It is required by law', false], ['It saves fuel', false]], exp: 'Applying trailer brakes with the hand valve can help straighten a swaying rig without dragging the tractor.' },
  { q: 'When parking doubles or triples, you should:', answers: [['Park on level ground and avoid backing if possible', true], ['Park on a slope to save space', false], ['Leave the engine running', false], ['Disconnect all trailers', false]], exp: 'Level ground reduces roll-away risk. Plan your parking so you can pull forward to leave — backing is hazardous.' },
  { q: 'What can cause the rear trailer to swing out on a curve?', answers: [['Taking the curve too fast', true], ['Slowing down too much', false], ['Using the hand valve', false], ['Having a heavy load', false]], exp: 'Excessive speed on curves causes the rear trailer to cut inside or swing outside. Slow down before curves.' },
  { q: 'Where are doubles and triples prohibited or restricted?', answers: [['In some states, on certain roads, and in some cities', true], ['Nowhere — they are legal everywhere', false], ['Only at night', false], ['Only on interstate highways', false]], exp: 'State laws vary. Some states ban triples; others restrict where doubles/triples may operate. Know the rules for your route.' },
  { q: 'How does wind affect doubles and triples?', answers: [['Crosswinds can cause significant sway — reduce speed', true], ['Wind has no effect', false], ['Wind improves stability', false], ['Only headwinds matter', false]], exp: 'Crosswinds push the tall, long trailers. Reduce speed in windy conditions and be ready to correct.' },
  { q: 'What should you do if the rear trailer starts to sway?', answers: [['Release the accelerator and apply the trailer hand valve gently', true], ['Accelerate to straighten it', false], ['Brake the tractor hard', false], ['Steer sharply', false]], exp: 'Ease off the accelerator. Use the trailer hand valve gently to dampen the sway. Avoid sudden braking or steering.' },
  { q: 'When coupling a second trailer, you should:', answers: [['Ensure the dolly is centered and the jaws are locked on the kingpin', true], ['Back under at full speed', false], ['Skip the brake test', false], ['Only connect the air lines', false]], exp: 'Center the dolly fifth wheel on the pup kingpin. Verify the jaws lock. Connect air and electrical, then test the brakes.' },
  { q: 'Why is a thorough pre-trip critical for doubles and triples?', answers: [['More connections and components mean more potential failure points', true], ['It takes longer', false], ['DOT requires extra paperwork', false], ['The cargo is heavier', false]], exp: 'Multiple trailers mean more couplings, air lines, and lights. Each connection is a potential failure point.' },
  { q: 'What is the best way to avoid problems with doubles and triples?', answers: [['Drive smoothly, plan ahead, and maintain proper speed', true], ['Stay in the left lane', false], ['Use the brakes frequently', false], ['Avoid highways', false]], exp: 'Smooth, anticipatory driving and appropriate speed minimize the risks of sway and jackknife.' },
]

const PASSENGER_QUESTIONS = [
  { q: 'What does the Passenger (P) endorsement allow you to drive?', answers: [['Vehicles designed to carry 16 or more passengers (including the driver)', true], ['Any vehicle with passengers', false], ['Only buses', false], ['Vehicles with 10 or more passengers', false]], exp: 'The P endorsement is required for vehicles designed to carry 16+ people (driver included). Buses, shuttle vans, etc.' },
  { q: 'Before driving a bus, what must you do regarding standees?', answers: [['Ensure they know where handholds are and have room to brace', true], ['Let them stand anywhere', false], ['Never allow standees', false], ['Only secure luggage', false]], exp: 'Standees need handholds or stanchions and space to brace. You are responsible for their safety.' },
  { q: 'When should you refuse to move a bus?', answers: [['When it is overloaded, has an unsafe condition, or standees cannot hold on', true], ['Only when the engine overheats', false], ['Never — you must always move', false], ['Only in bad weather', false]], exp: 'Do not move if the bus is overloaded, has defects, or standees cannot safely hold on. Your call.' },
  { q: 'What is a "standee line"?', answers: [['A line inside the bus indicating where standees may not stand (behind the driver)', true], ['A line to board the bus', false], ['A line on the road', false], ['A painted stripe on the bus exterior', false]], exp: 'The standee line marks the area where standing is not allowed — usually forward of the line to protect the driver and allow visibility.' },
  { q: 'How often must you inspect the emergency exits on a bus?', answers: [['Every trip, as part of your pre-trip', true], ['Once a week', false], ['Only when carrying passengers', false], ['Only at the garage', false]], exp: 'Emergency exits must be checked on every pre-trip. Blocked or broken exits are a serious safety violation.' },
  { q: 'What should you do if a passenger becomes disruptive?', answers: [['Pull over safely, stop, and deal with the situation before continuing', true], ['Keep driving and ignore them', false], ['Speed up to get to the destination', false], ['Make them get off at the next stop', false]], exp: 'Stop in a safe place. Deal with the situation. Do not drive with a disruptive passenger — it endangers everyone.' },
  { q: 'Why must bus drivers be especially careful with acceleration and braking?', answers: [['Passengers can fall or be thrown if you are not smooth', true], ['The bus has weak brakes', false], ['It saves fuel', false], ['DOT requires it', false]], exp: 'Passengers are not secured like cargo. Sudden acceleration or braking can cause falls and injuries.' },
  { q: 'What is the proper way to handle Railroad Crossings with a bus?', answers: [['Stop, look, listen — and never proceed until it is clear', true], ['Slow down and proceed', false], ['Only stop if a train is visible', false], ['Honk and go', false]], exp: 'Buses (and school buses) must stop at RR crossings. Look and listen. Never proceed until you are certain it is safe.' },
  { q: 'Who is responsible for the safety of passengers on a bus?', answers: [['The driver', true], ['The company only', false], ['The passengers', false], ['The dispatcher', false]], exp: 'The driver has primary responsibility for passenger safety — loading, securing, and operating the vehicle safely.' },
  { q: 'When may you use the bus\'s hazard lights?', answers: [['When stopped on or near the roadway to warn other traffic', true], ['Anytime you want', false], ['Never', false], ['Only when changing tires', false]], exp: 'Hazard lights warn other drivers that the bus is stopped or moving slowly. Use them when appropriate.' },
  { q: 'What should you do before leaving a bus with passengers aboard?', answers: [['Secure the bus (brakes, ignition) and ensure passengers know the rules', true], ['Just turn off the engine', false], ['Leave the keys in the ignition', false], ['Never leave the bus with passengers', false]], exp: 'Set the parking brake, turn off the engine, remove the key. Tell passengers not to tamper with emergency exits.' },
  { q: 'How should you position the bus when loading or unloading passengers?', answers: [['So passengers can board and exit safely, away from traffic', true], ['As close to traffic as possible', false], ['In the middle of the lane', false], ['Wherever is convenient', false]], exp: 'Load and unload in safe locations. Avoid blocking crosswalks or forcing passengers into traffic.' },
  { q: 'What is a "danger zone" around a bus?', answers: [['The area around the bus where the driver cannot see people', true], ['The area inside the bus', false], ['The engine compartment', false], ['The luggage area', false]], exp: 'The danger zone includes blind spots around the bus. You must account for it when moving or loading.' },
  { q: 'Before pulling away from a bus stop, you should:', answers: [['Check mirrors for pedestrians and vehicles, then signal and proceed slowly', true], ['Honk and go', false], ['Pull out quickly', false], ['Wait for a gap in traffic only', false]], exp: 'Check mirrors for people near the bus (especially children). Signal, then pull away slowly and carefully.' },
  { q: 'What should you do if a passenger needs medical help?', answers: [['Stop safely, call for help, and assist within your training', true], ['Drive to the hospital', false], ['Ignore it', false], ['Only call your company', false]], exp: 'Stop in a safe place. Call 911. Provide aid within your training. Do not drive with a medical emergency unless directed.' },
  { q: 'Why must luggage and carry-on items be secured on a bus?', answers: [['They can become projectiles in a crash or sudden stop', true], ['To prevent theft', false], ['DOT requires it', false], ['Only for long trips', false]], exp: 'Unsecured items can fly forward and injure passengers. Secure everything properly.' },
  { q: 'What is the proper procedure when approaching a bus stop?', answers: [['Signal early, reduce speed, and stop smoothly at the correct location', true], ['Stop suddenly', false], ['Do not signal', false], ['Speed up to make up time', false]], exp: 'Signal in advance. Slow smoothly. Stop where passengers can board safely. Avoid sudden movements.' },
  { q: 'When may passengers stand on a bus?', answers: [['Only when there are no seats and they can hold on safely', true], ['Never', false], ['Anytime', false], ['Only in the rear', false]], exp: 'Standees are allowed only when seats are full and they have handholds and room to brace. Follow your company and state rules.' },
  { q: 'What should you do if you see a vehicle passing you in a no-passing zone?', answers: [['Slow down to give them room to complete the pass safely', true], ['Speed up', false], ['Move to the left', false], ['Honk repeatedly', false]], exp: 'Resist the urge to speed up. Easing off can help the other vehicle complete an illegal pass more quickly and safely.' },
  { q: 'How does the center of gravity of a bus differ from a truck?', answers: [['Passengers raise the center of gravity, making rollover more likely', true], ['It is lower', false], ['There is no difference', false], ['Buses cannot roll over', false]], exp: 'A loaded bus has a higher center of gravity. Sharp turns or sudden swerves increase rollover risk.' },
  { q: 'What is the proper way to handle a tire blowout on a bus?', answers: [['Hold the wheel firmly, ease off the accelerator, and brake gently when under control', true], ['Brake hard', false], ['Turn sharply', false], ['Accelerate', false]], exp: 'Hold the wheel. Ease off the gas. Do not brake until the bus is straight. Then brake gently.' },
  { q: 'Before each trip, a bus driver should:', answers: [['Complete a thorough pre-trip including interior and emergency equipment', true], ['Only check the engine', false], ['Trust the mechanic', false], ['Skip the interior', false]], exp: 'Pre-trip must include interior checks, emergency exits, fire extinguisher, first aid kit, and all safety equipment.' },
  { q: 'What should you do if smoke or fire is detected in the bus?', answers: [['Evacuate passengers immediately to a safe distance', true], ['Keep driving', false], ['Open windows only', false], ['Wait for the fire department', false]], exp: 'Get everyone off the bus quickly and move them to a safe distance. Call for help. Do not re-enter if there is fire.' },
]

const SCHOOL_BUS_QUESTIONS = [
  { q: 'What additional requirements apply to school bus drivers beyond the Passenger endorsement?', answers: [['Extra training, background checks, and knowledge of school bus-specific rules', true], ['Nothing — the P endorsement is enough', false], ['Only a clean driving record', false], ['A college degree', false]], exp: 'School bus drivers typically need additional state training, background checks, and knowledge of loading/unloading and emergency procedures.' },
  { q: 'When must you stop for a school bus with flashing red lights?', answers: [['When the bus is loading or unloading and the stop arm is out', true], ['Only when children are visible', false], ['Only on two-lane roads', false], ['Never — you can pass slowly', false]], exp: 'Flashing red lights and extended stop arm mean you must stop. This applies to traffic in both directions on most roads.' },
  { q: 'How far behind or in front of a school bus should you stop when it has red lights flashing?', answers: [['At least 20 feet in most states', true], ['10 feet', false], ['5 feet', false], ['As close as possible', false]], exp: 'State laws vary; 20 feet is common. Stay back far enough that children have room to cross safely.' },
  { q: 'What does the alternating flashing yellow light on a school bus mean?', answers: [['The bus is preparing to stop — slow down and be ready to stop', true], ['The bus is turning', false], ['There is a mechanical problem', false], ['You may pass', false]], exp: 'Yellow flashing lights mean the bus is about to stop. Slow down and prepare to stop.' },
  { q: 'What is the "danger zone" around a school bus?', answers: [['The area around the bus where children are most at risk — 10 feet on all sides', true], ['The area inside the bus', false], ['The engine compartment', false], ['Only in front of the bus', false]], exp: 'The danger zone is typically 10 feet around the bus. The driver must account for it when moving and when children are loading/unloading.' },
  { q: 'When loading or unloading students, what should the driver do?', answers: [['Count students, ensure they are clear of the danger zone, and watch mirrors before moving', true], ['Rely on the crossing guard only', false], ['Honk and go', false], ['Never use mirrors', false]], exp: 'Count students. Ensure they are away from the bus. Check all mirrors. Only then may you move.' },
  { q: 'How many times should you count students when loading?', answers: [['At least twice — when they board and before you move', true], ['Once', false], ['Only at the school', false], ['Five times', false]], exp: 'Count when they board. Count again (or verify) before you move. Never move until you know where every child is.' },
  { q: 'What should you do if a student is missing when you arrive at school?', answers: [['Notify the school or authorities — never leave with a missing student unaccounted for', true], ['Assume they got off at the wrong stop', false], ['Continue your route', false], ['Only tell the next driver', false]], exp: 'Report a missing student immediately. Do not assume they are safe. Follow your district\'s procedures.' },
  { q: 'When may you leave the bus with the engine running?', answers: [['Never when students are aboard', true], ['When you are only a few feet away', false], ['When loading', false], ['At the school only', false]], exp: 'Never leave the engine running with students on board. Turn it off, set the brake, and take the key when you leave.' },
  { q: 'What emergency equipment must a school bus have?', answers: [['First aid kit, fire extinguisher, emergency reflectors, body fluid cleanup kit', true], ['Only a first aid kit', false], ['Nothing special', false], ['Only a fire extinguisher', false]], exp: 'School buses must have first aid, fire extinguisher, reflectors/triangles, and often body fluid cleanup supplies.' },
  { q: 'What should you do during a bus evacuation drill?', answers: [['Follow the established procedure and ensure all students exit safely', true], ['Skip it if you are behind schedule', false], ['Only practice with older students', false], ['Let students figure it out', false]], exp: 'Evacuation drills are required. Practice the procedure. Ensure every student knows how to exit quickly and safely.' },
  { q: 'When students are crossing the road in front of the bus, you should:', answers: [['Wait until they are completely across and signals are off before moving', true], ['Start moving as soon as they step off', false], ['Honk to hurry them', false], ['Move as soon as the last student exits', false]], exp: 'Wait until all students are safely across. The stop arm and lights must stay on until they are clear.' },
  { q: 'What is the proper way to handle a medical emergency involving a student?', answers: [['Stop the bus, call for help, and provide aid within your training', true], ['Drive to the hospital', false], ['Wait for the nurse', false], ['Ignore minor injuries', false]], exp: 'Stop safely. Call 911. Provide first aid within your training. Have someone contact the school.' },
  { q: 'Why must school bus drivers maintain strict discipline?', answers: [['Disorder can distract the driver and endanger everyone', true], ['To punish students', false], ['Because the school says so', false], ['Only on long trips', false]], exp: 'A disruptive bus is unsafe. Anyone distracting the driver puts the entire bus at risk.' },
  { q: 'What should you do if you see a vehicle that did not stop for the school bus?', answers: [['Record the plate number and description, report it to authorities', true], ['Chase the vehicle', false], ['Ignore it', false], ['Honk only', false]], exp: 'Get the license plate and vehicle description. Report to police and your supervisor. Many states have severe penalties for this.' },
  { q: 'When backing a school bus, you should:', answers: [['Only when necessary, with a spotter, and after checking the danger zone', true], ['Back quickly', false], ['Never use a spotter', false], ['Back without looking', false]], exp: 'Avoid backing when possible. If you must back, use a spotter and verify the danger zone is clear.' },
  { q: 'What is the purpose of the crossing arm on a school bus?', answers: [['To extend in front of the bus to force children to walk where the driver can see them', true], ['To block traffic', false], ['To support the bus', false], ['For decoration', false]], exp: 'The crossing arm extends so children must walk in front of the bus, in the driver\'s view, when crossing.' },
  { q: 'How often should school bus emergency equipment be checked?', answers: [['Every day as part of the pre-trip', true], ['Once a month', false], ['Only when needed', false], ['At the start of the school year only', false]], exp: 'Check first aid, fire extinguisher, and emergency equipment daily during your pre-trip.' },
  { q: 'When are you required to use your headlights on a school bus?', answers: [['When required by state law — often whenever the bus is in operation', true], ['Only at night', false], ['Never', false], ['Only in bad weather', false]], exp: 'Many states require headlights on whenever the bus is running. Know your state\'s rules.' },
  { q: 'What should you do if a child runs toward the bus as you are about to pull away?', answers: [['Wait — never leave a stop if a child is running toward the bus', true], ['Honk and wait a moment', false], ['Leave — they missed the bus', false], ['Wave them off', false]], exp: 'If a child is running toward the bus, wait. Do not pull away until they are either on board or safely away.' },
]

const TANK_QUESTIONS = [
  { q: 'What does the Tank (N) endorsement allow you to haul?', answers: [['Liquid or gaseous materials in bulk tanks permanently attached to the vehicle', true], ['Any liquid cargo', false], ['Only fuel', false], ['Dry bulk only', false]], exp: 'The N endorsement covers liquid or gaseous materials in bulk tanks that are permanently attached. Different from portable tanks.' },
  { q: 'What causes "surge" in a tank vehicle?', answers: [['Liquid moving back and forth when the vehicle slows, speeds up, or turns', true], ['Air pressure in the tank', false], ['The brakes', false], ['The engine', false]], exp: 'Surge is the liquid sloshing. It can push the vehicle and make it harder to control. Drive smoothly to minimize surge.' },
  { q: 'How does surge affect braking?', answers: [['The liquid can push the vehicle forward, increasing stopping distance', true], ['It has no effect', false], ['It shortens stopping distance', false], ['It locks the brakes', false]], exp: 'When you brake, the liquid surges forward. That momentum can push the truck and lengthen your stop.' },
  { q: 'When starting from a stop with a loaded tank, you should:', answers: [['Accelerate slowly to avoid surge', true], ['Accelerate quickly', false], ['Use the clutch only', false], ['Let the truck roll first', false]], exp: 'Smooth acceleration reduces surge. Jerky starts cause the liquid to slosh and can make the truck harder to control.' },
  { q: 'When stopping a tank vehicle, you should:', answers: [['Brake early and gently to reduce surge', true], ['Brake hard at the last moment', false], ['Use only the parking brake', false], ['Downshift without braking', false]], exp: 'Brake early and gently. Sudden braking causes surge, which can push the vehicle or cause loss of control.' },
  { q: 'Why is a partially loaded tank often more dangerous than a full one?', answers: [['The liquid has more room to slosh, creating more surge', true], ['It is lighter', false], ['The tank can collapse', false], ['It is not more dangerous', false]], exp: 'Partially full tanks have more "free surface" — the liquid can move more. This increases surge and instability.' },
  { q: 'What are "baffles" in a tank?', answers: [['Bulkheads inside the tank that limit liquid movement', true], ['The fill openings', false], ['The valves', false], ['The tank supports', false]], exp: 'Baffles (bulkheads) reduce surge by limiting how far the liquid can move. Some tanks have none — "smooth bore" — and surge more.' },
  { q: 'What is a "smooth bore" tank?', answers: [['A tank with no baffles — liquid can move freely', true], ['A tank with a smooth exterior', false], ['A rounded tank', false], ['A tank for water only', false]], exp: 'Smooth bore tanks have no baffles. The liquid surges more. Drive even more carefully with smooth bore tanks.' },
  { q: 'When turning with a tank vehicle, you should:', answers: [['Slow down well before the turn and take it smoothly', true], ['Turn sharply', false], ['Speed up through the turn', false], ['Use the brakes in the turn', false]], exp: 'Slow before the turn. Surge in a turn can push the vehicle and cause rollover or loss of control.' },
  { q: 'What is the proper way to fill a tank?', answers: [['Match the product to the tank, secure the load, and ensure vents and valves are correct', true], ['Fill as fast as possible', false], ['Overfill to prevent surge', false], ['Only check the level', false]], exp: 'Verify you are loading the correct product. Secure all openings. Ensure vents work. Never overfill.' },
  { q: 'Why must you know the tank\'s outage or fill level?', answers: [['Overfilling can cause leaks or rupture from thermal expansion', true], ['To save money', false], ['DOT does not require it', false], ['Only for hazardous materials', false]], exp: 'Liquids expand when heated. Outage (empty space) allows for expansion. Overfilling can cause failure.' },
  { q: 'What should you check on a tank vehicle during a pre-trip?', answers: [['Leaks, tank supports, valves, vents, and emergency equipment', true], ['Only the tank exterior', false], ['Only the valves', false], ['Nothing — tanks are sealed', false]], exp: 'Check for leaks, secure mounting, valve operation, vent condition, and emergency equipment.' },
  { q: 'When hauling flammable liquids in a tank, what extra precautions apply?', answers: [['Ground the vehicle during loading, no smoking, proper placards', true], ['No special precautions', false], ['Only avoid sparks', false], ['Only use at night', false]], exp: 'Grounding prevents static sparks. No smoking or ignition sources. Placard correctly. Follow hazmat rules.' },
  { q: 'What causes rollover in tank vehicles?', answers: [['Surge shifting the center of gravity, especially in turns', true], ['Only brake failure', false], ['Overloading', false], ['Wind only', false]], exp: 'Surge can shift the liquid to one side, raising the center of gravity and increasing rollover risk in curves.' },
  { q: 'How does the center of gravity change in a tank truck?', answers: [['It shifts as the liquid moves — high when sloshing', true], ['It never changes', false], ['It is always low', false], ['Only when empty', false]], exp: 'As liquid surges, the center of gravity moves. In a turn, liquid can shift to one side and raise it, increasing rollover risk.' },
  { q: 'What is the "outage" for a tank?', answers: [['The empty space left for liquid expansion', true], ['The amount of product', false], ['The tank capacity', false], ['The fill opening', false]], exp: 'Outage is the unfilled space. It allows the liquid to expand when heated without rupturing the tank.' },
  { q: 'When descending a grade with a tank vehicle, you should:', answers: [['Use a low gear and brake gently before the grade gets steep', true], ['Ride the brakes', false], ['Use neutral', false], ['Accelerate', false]], exp: 'Use a low gear for engine braking. Apply brakes gently and early. Surge on a grade can push you downhill.' },
  { q: 'What should you do if you notice a leak in the tank or valves?', answers: [['Stop safely, identify the leak, and get help — do not drive', true], ['Continue to the destination', false], ['Tighten the valves and continue', false], ['Only if it is a large leak', false]], exp: 'Do not drive with a leak. Stop. Identify the source. Call for help. A leaking tank is a safety and environmental hazard.' },
  { q: 'Why should you avoid sudden lane changes with a tank vehicle?', answers: [['Surge can cause the vehicle to sway or roll', true], ['It is illegal', false], ['It wastes fuel', false], ['It has no effect', false]], exp: 'Sudden steering causes surge. The liquid shifts, which can make the truck sway or contribute to rollover.' },
  { q: 'What type of tank has the most surge?', answers: [['A smooth bore tank that is half full', true], ['A full baffled tank', false], ['An empty tank', false], ['A tank with three compartments', false]], exp: 'Smooth bore = no baffles. Half full = lots of room to slosh. That combination produces the most surge.' },
  { q: 'When loading a tank, why is it important to know the product?', answers: [['Different products have different requirements for fill level, compatibility, and hazmat', true], ['Only for billing', false], ['DOT does not care', false], ['Only for weight', false]], exp: 'Some products expand more. Some require special handling. Some are hazmat. Always verify the product.' },
]

const TESTS = [
  { slug: 'cdl-general-knowledge-practice-test', endorsement: 'general-knowledge', title: 'CDL General Knowledge Practice Test — 25 Questions (2026)', description: 'Practice the most commonly tested topics from the CDL General Knowledge exam. Covers vehicle inspection, cargo, braking, and driving safely.', questions: GENERAL_KNOWLEDGE_QUESTIONS },
  { slug: 'cdl-air-brakes-practice-test', endorsement: 'air-brakes', title: 'CDL Air Brakes Practice Test — 26 Questions (2026)', description: 'Study for the CDL Air Brakes endorsement. Covers air brake system components, pre-trip checks, pushrod stroke, loss of air pressure, and combination vehicle air brakes.', questions: AIR_BRAKES_QUESTIONS },
  { slug: 'cdl-hazmat-practice-test', endorsement: 'hazmat', title: 'CDL HazMat Practice Test — 26 Questions (2026)', description: 'Study for the CDL Hazardous Materials endorsement. Covers placarding, shipping papers, hazard classes, loading/unloading, parking rules, and emergency response.', questions: HAZMAT_QUESTIONS },
  { slug: 'cdl-combination-vehicles-practice-test', endorsement: 'combination', title: 'CDL Combination Vehicles Practice Test — 26 Questions (2026)', description: 'Study for the CDL Combination Vehicles endorsement. Covers fifth wheel coupling, air lines, backing, and safe operation of tractor-trailer combinations.', questions: COMBINATION_QUESTIONS },
  { slug: 'cdl-doubles-triples-practice-test', endorsement: 'doubles-triples', title: 'CDL Doubles & Triples Practice Test — 21 Questions (2026)', description: 'Study for the CDL Doubles and Triples endorsement. Covers handling multiple trailers, crack-the-whip effect, sway control, and state-specific rules.', questions: DOUBLES_TRIPLES_QUESTIONS },
  { slug: 'cdl-passenger-practice-test', endorsement: 'passenger', title: 'CDL Passenger Transport Practice Test — 22 Questions (2026)', description: 'Study for the CDL Passenger (P) endorsement. Covers bus operation, passenger safety, loading/unloading, and emergency procedures.', questions: PASSENGER_QUESTIONS },
  { slug: 'cdl-school-bus-practice-test', endorsement: 'school-bus', title: 'CDL School Bus Practice Test — 20 Questions (2026)', description: 'Study for the CDL School Bus endorsement. Covers loading/unloading students, danger zone, crossing procedures, and school bus-specific safety.', questions: SCHOOL_BUS_QUESTIONS },
  { slug: 'cdl-tank-vehicles-practice-test', endorsement: 'tank', title: 'CDL Tank Vehicles Practice Test — 21 Questions (2026)', description: 'Study for the CDL Tank (N) endorsement. Covers surge, baffles, smooth bore tanks, and safe handling of liquid cargo.', questions: TANK_QUESTIONS },
]

async function main() {
  try {
    const payload = await getPayload({ config })

    for (const test of TESTS) {
      const existing = await payload.find({
        collection: 'practice-tests',
        where: { slug: { equals: test.slug } },
        limit: 1,
      })

      if (existing.docs.length > 0) {
        console.log(`[seed] ${test.title} already exists. Skipping.`)
        continue
      }

      const questions = test.questions.map((item) => ({
        question: item.q,
        answers: item.answers.map(([text, correct]) => ({ text, correct })),
        explanation: item.exp,
      }))

      await payload.create({
        collection: 'practice-tests',
        data: {
          title: test.title,
          slug: test.slug,
          endorsement: test.endorsement,
          description: test.description,
          questions,
          status: 'published',
        },
      })

      console.log(`[seed] ${test.title} created with ${test.questions.length} questions.`)
    }

    console.log('[seed] All 8 CDL practice tests complete.')
    process.exit(0)
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err)
    console.error('[seed] Error:', message)
    process.exit(1)
  }
}

main()
