/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    articles: Article;
    posts: Post;
    'practice-tests': PracticeTest;
    categories: Category;
    media: Media;
    'service-intervals': ServiceInterval;
    'feed-sources': FeedSource;
    'news-links': NewsLink;
    'processed-news-items': ProcessedNewsItem;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'practice-tests': PracticeTestsSelect<false> | PracticeTestsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'service-intervals': ServiceIntervalsSelect<false> | ServiceIntervalsSelect<true>;
    'feed-sources': FeedSourcesSelect<false> | FeedSourcesSelect<true>;
    'news-links': NewsLinksSelect<false> | NewsLinksSelect<true>;
    'processed-news-items': ProcessedNewsItemsSelect<false> | ProcessedNewsItemsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Career guides and CDL-by-state content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * URL slug (e.g. "how-to-get-cdl-georgia")
   */
  slug: string;
  /**
   * Short description shown on listing pages and in Google search results (150–160 chars).
   */
  excerpt: string;
  featuredImage?: (number | null) | Media;
  category: number | Category;
  /**
   * CDL endorsements this guide relates to. Used to show related practice tests and vice versa.
   */
  relatedEndorsements?:
    | (
        | 'general-knowledge'
        | 'air-brakes'
        | 'hazmat'
        | 'combination'
        | 'doubles-triples'
        | 'passenger'
        | 'school-bus'
        | 'tank'
      )[]
    | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo?: {
    /**
     * Overrides the page title in search results (60 chars max).
     */
    metaTitle?: string | null;
    /**
     * Shown under the link in Google results (155 chars max).
     */
    metaDescription?: string | null;
  };
  publishedAt?: string | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL-friendly identifier (e.g. "cdl-test-prep")
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog posts — news, tips, and updates for truckers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Auto-generated from title. Leave blank to generate from title.
   */
  slug?: string | null;
  /**
   * Short description for listing pages and search (150–160 chars).
   */
  excerpt: string;
  /**
   * Main image for the post. Shown in listings and social previews.
   */
  featuredImage?: (number | null) | Media;
  /**
   * Who wrote this post.
   */
  author?: (number | null) | User;
  /**
   * Paste or write HTML for the post body.
   */
  content: string;
  seo?: {
    /**
     * Overrides the page title in search results (60 chars max).
     */
    metaTitle?: string | null;
    /**
     * Shown under the link in Google results (155 chars max).
     */
    metaDescription?: string | null;
    /**
     * Paste JSON-LD schema markup (e.g. Article, FAQPage). This will be injected into the page as a <script type="application/ld+json"> tag.
     */
    structuredData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  publishedAt?: string | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * CDL practice tests grouped by endorsement type.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practice-tests".
 */
export interface PracticeTest {
  id: number;
  /**
   * e.g. "CDL General Knowledge Practice Test — 100 Questions"
   */
  title: string;
  slug: string;
  endorsement:
    | 'general-knowledge'
    | 'air-brakes'
    | 'hazmat'
    | 'combination'
    | 'doubles-triples'
    | 'passenger'
    | 'school-bus'
    | 'tank';
  /**
   * Shown at the top of the test page.
   */
  description?: string | null;
  questions: {
    question: string;
    answers: {
      text: string;
      correct?: boolean | null;
      id?: string | null;
    }[];
    /**
     * Shown after answering, explains why the correct answer is right.
     */
    explanation?: string | null;
    id?: string | null;
  }[];
  /**
   * Auto-calculated from questions array.
   */
  questionCount?: number | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Truck and engine service interval guidelines. One document per PDF or source.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-intervals".
 */
export interface ServiceInterval {
  id: number;
  /**
   * Display name, e.g. "Volvo VNL 2022+", "Cummins X15 Efficiency", "PACCAR MX-13"
   */
  name: string;
  type: 'engine' | 'truck';
  /**
   * Manufacturer: Volvo, Cummins, PACCAR, Detroit, Peterbilt, etc.
   */
  make: string;
  /**
   * Engine or truck model: X15, MX-13, VNL, VNR, T680, DD13, DD15
   */
  model?: string | null;
  /**
   * Year applicability: "2017–2020", "2021 and newer", "Model year 2011+", "Gen 5"
   */
  yearRange?: string | null;
  /**
   * EPA level, oil spec, duty definitions, or other context
   */
  applicability?: string | null;
  /**
   * Attach the source PDF when available
   */
  sourcePdf?: (number | null) | Media;
  /**
   * URL for web-only sources (e.g. DTNA Tech Lit) when no PDF
   */
  sourceUrl?: string | null;
  intervals: {
    section: 'engine' | 'coolant' | 'exhaust' | 'transmission' | 'chassis' | 'miscellaneous' | 'other';
    /**
     * e.g. "Engine oil, filters, fuel filters"
     */
    service: string;
    /**
     * e.g. "60,000 / 45,000 / 35,000 mi" or "40,000 miles"
     */
    interval: string;
    /**
     * e.g. "Normal / Heavy / Severe" — explains interval columns
     */
    dutyNote?: string | null;
    notes?: string | null;
    id?: string | null;
  }[];
  /**
   * Only published documents appear in the search tool
   */
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * RSS feeds for the Truckers News page. Add or disable sources here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feed-sources".
 */
export interface FeedSource {
  id: number;
  /**
   * Display name, e.g. "Fleet Owner", "FMCSA"
   */
  name: string;
  /**
   * Full RSS or Atom feed URL
   */
  feedUrl: string;
  /**
   * Optional category for grouping
   */
  category?: ('regulations' | 'freight' | 'equipment' | 'safety' | 'technology' | 'general') | null;
  /**
   * Uncheck to stop fetching this feed without deleting it
   */
  enabled?: boolean | null;
  /**
   * Order in admin list (lower = first)
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manually curated links for the Truckers News page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-links".
 */
export interface NewsLink {
  id: number;
  /**
   * Headline text (shown as link)
   */
  title: string;
  /**
   * Full URL (external) or path (e.g. /blog/my-post)
   */
  url: string;
  /**
   * Source label, e.g. "The Truckers Edge"
   */
  source?: string | null;
  /**
   * Optional category for grouping
   */
  category?: ('regulations' | 'freight' | 'equipment' | 'safety' | 'technology' | 'general') | null;
  /**
   * Used for sorting (most recent first)
   */
  publishedAt?: string | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * AI-processed RSS items. Override headline or hide from the news page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "processed-news-items".
 */
export interface ProcessedNewsItem {
  id: number;
  /**
   * Unique URL (dedup key)
   */
  url: string;
  originalTitle: string;
  /**
   * AI-generated catchy headline
   */
  rewrittenTitle?: string | null;
  /**
   * AI score 1-10 for viral potential
   */
  viralScore?: number | null;
  /**
   * Override: when set, displayed instead of AI rewrite
   */
  headlineOverride?: string | null;
  /**
   * Hide this item from the news page
   */
  hidden?: boolean | null;
  source: string;
  publishedAt?: string | null;
  /**
   * When AI processed this item
   */
  processedAt?: string | null;
  /**
   * Generated with the headline for search/social; edit if needed.
   */
  seo?: {
    /**
     * Title tag / SERP title (~50–60 characters).
     */
    metaTitle?: string | null;
    /**
     * Meta description for search snippets (~150–160 characters).
     */
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'practice-tests';
        value: number | PracticeTest;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'service-intervals';
        value: number | ServiceInterval;
      } | null)
    | ({
        relationTo: 'feed-sources';
        value: number | FeedSource;
      } | null)
    | ({
        relationTo: 'news-links';
        value: number | NewsLink;
      } | null)
    | ({
        relationTo: 'processed-news-items';
        value: number | ProcessedNewsItem;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  category?: T;
  relatedEndorsements?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  publishedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  author?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        structuredData?: T;
      };
  publishedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practice-tests_select".
 */
export interface PracticeTestsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  endorsement?: T;
  description?: T;
  questions?:
    | T
    | {
        question?: T;
        answers?:
          | T
          | {
              text?: T;
              correct?: T;
              id?: T;
            };
        explanation?: T;
        id?: T;
      };
  questionCount?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-intervals_select".
 */
export interface ServiceIntervalsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  make?: T;
  model?: T;
  yearRange?: T;
  applicability?: T;
  sourcePdf?: T;
  sourceUrl?: T;
  intervals?:
    | T
    | {
        section?: T;
        service?: T;
        interval?: T;
        dutyNote?: T;
        notes?: T;
        id?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feed-sources_select".
 */
export interface FeedSourcesSelect<T extends boolean = true> {
  name?: T;
  feedUrl?: T;
  category?: T;
  enabled?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-links_select".
 */
export interface NewsLinksSelect<T extends boolean = true> {
  title?: T;
  url?: T;
  source?: T;
  category?: T;
  publishedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "processed-news-items_select".
 */
export interface ProcessedNewsItemsSelect<T extends boolean = true> {
  url?: T;
  originalTitle?: T;
  rewrittenTitle?: T;
  viralScore?: T;
  headlineOverride?: T;
  hidden?: T;
  source?: T;
  publishedAt?: T;
  processedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}